import { DOCS_NAMES, FIELD_NAMES } from '../../../form/types.ts'

export const AML_POLICY_NAME = `${FIELD_NAMES.DOCUMENTS}.${DOCS_NAMES.AML_POLICY}`
export const DATA_PROTECTION_POLICY_NAME = `${FIELD_NAMES.DOCUMENTS}.${DOCS_NAMES.DATA_PROTECTION_POLICY}`
export const TERMS_AND_CONDITIONS_NAME = `${FIELD_NAMES.DOCUMENTS}.${DOCS_NAMES.TERMS_AND_CONDITIONS}`
export const REFUND_POLICY_NAME = `${FIELD_NAMES.DOCUMENTS}.${DOCS_NAMES.REFUND_POLICY}`
export const INVESTOR_ACCREDITED_STATUS_NAME = `${FIELD_NAMES.DOCUMENTS}.${DOCS_NAMES.INVESTOR_ACCREDITED_STATUS}`
